// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeCard: typeof import('./src/components/CodeCard/CodeCard.vue')['default']
    Drawer: typeof import('./src/components/Drawer/Drawer.vue')['default']
    Echarts: typeof import('./src/components/Echarts/Echarts.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect/IconSelect.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    MilkDown: typeof import('./src/components/MilkDown/MilkDown.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    SimplePagination: typeof import('./src/components/Pagination/SimplePagination.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    TableSet: typeof import('./src/components/BasicTable/components/TableSet.vue')['default']
    TransRouterView: typeof import('./src/components/TransRouterView/TransRouterView.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/WangEditor.vue')['default']
  }
}

export { }
