/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeCard: typeof import('./../src/components/CodeCard/CodeCard.vue')['default']
    Drawer: typeof import('./../src/components/Drawer/Drawer.vue')['default']
    Echarts: typeof import('./../src/components/Echarts/Echarts.vue')['default']
    Icon: typeof import('./../src/components/Icon/Icon.vue')['default']
    IconSelect: typeof import('./../src/components/IconSelect/IconSelect.vue')['default']
    LazyInput: typeof import('./../src/components/LazyInput/LazyInput.vue')['default']
    Middleware: typeof import('./../src/components/FormRender/components/Middleware.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplePagination: typeof import('./../src/components/Pagination/SimplePagination.vue')['default']
    SvgIcon: typeof import('./../src/components/Icon/SvgIcon.vue')['default']
    TableRender: typeof import('./../src/components/TableRender/TableRender.vue')['default']
    TableSet: typeof import('./../src/components/TableRender/components/TableSet.vue')['default']
    TableTool: typeof import('./../src/components/TableRender/components/TableTool.vue')['default']
    TransRouterView: typeof import('./../src/components/TransRouterView/TransRouterView.vue')['default']
    WangEditor: typeof import('./../src/components/WangEditor/WangEditor.vue')['default']
  }
}
